blog-management-system-master/blog-management-system-master/blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    url(r'^result/$', search, name='search'),
    url(r'^blog-list/$', post_list, name='blog_list'),
    url(r'^blog-detail/(?P<slug>[-\w]+)/$', post_detail, name='blog_detail'),
    url(r'^category-detail/(?P<slug>[-\w]+)/$', category_detail, name='category_detail'),

    url(r'^new-post/$', new_post, name='new_post'),

    url(r'^post-list/$', post_list_admin, name='post_list_admin'),
    url(r'^edit-post/(?P<pk>\d+)/$', edit_post, name='edit_post'),
    url(r'^delete-post/(?P<pk>\d+)/$', delete_post, name='delete_post'),
]

blog-management-system-master/blog-management-system-master/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *
from blog.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home', home, name='home'),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog')),
    url(r'^login/', user_login, name="user_login"),
    url(r'^logout/', user_logout, name="user_logout"),
    url(r'^register/', user_register, name="user_register"),
    url(r'^final/', final, name="final"),
]

blog-management-system-master/blog-management-system-master/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block seo_title %}{% endblock %}</title>
    <meta name="description" content="{% block seo_description %}{% endblock %}">
          <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
          <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
         <!--Header-->
        <div class="navbar-header">

         <a style="background-color: cyan; color: blue;" class="navbar-brand btn btn-primary" href="{% url 'blog:new_post' %}">ADD New Post</a>
            <a style="background-color: blue; color: white;" class="navbar-brand btn btn-primary" href="{% url 'blog:post_list_admin' %}">Blog List</a>
        </div>


    <form class="col-md-8" method="get" action="{% url 'blog:search' %}">
            <input name="q" value="{{ request.GET.q }}" placeholder="Search..." class="">
        <button type="submit" class="btn btn-info">Search</button>
        </form>

    <form method="POST" action="/logout/">
    {% csrf_token %}
        <a href="">
                <span class="">{{ request.user.first_name }}</span>
            </a>
    <button style="background-color: red; color: white;" type="submit" class="btn btn-danger">Logout</button>
    </form>

</nav>

{% block content %}
{% endblock %}
</body>
</html>

blog-management-system-master/blog-management-system-master/templates/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Welcome in Djnago</title>
</head>
<body>
{% if request.GET.name %}
    <h1>{{ message }}</h1>
{% else %}
    <form method="get" action="{% url 'home' %}">
    <input name="name" value="{{request.GET.name}}">
    <button type="submit">Submit</button>
    </form>
    <h1>This is the home Page</h1>
{% endif %}
</body>
</html>

blog-management-system-master/blog-management-system-master/templates/pagination.html
{% if items.has_other_pages %}
    <div class="text-center">
        <div class="col-6 offset-3 text-center pagination-set">
            <nav aria-label="">
                <ul class="pagination" style="justify-content: center;">
                    {% if items.has_previous %}
                        <li class="page-item"><a class="page-link" style="background-color: #ffd536; color: #1e415e; border: #1e415e;" href="?page={{items.previous_page_number}}{% if query %}&q={{ query }}{% endif %}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link"
                                                          style="background-color: #ffd536; color: #1e415e; border: #1e415e;">
                            <span>&laquo;</span></a>
                        </li>
                    {% endif %}
                    {% for i in page_range %}
                        {% if items.number == i %}
                            <li class="page_item active"><a class="page-link"
                                                            style="background-color: #1e415e; border: #1e415e;" href="#">{{i}}
                                <span class="sr-only">(current)</span></a>
                            </li>
                        {% else %}
                            <li class="page-item"><a class="page-link"
                                                     style="background-color: #ffd536;
                                                     color: #1e415e; border: #1e415e;" href="?page={{i}}{% if query %}&q={{ query }}{% endif %}">{{i}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if items.has_next %}
                        <li class="page-item"><a class="page-link" style="background-color: #ffd536; color: #1e415e; border: #1e415e;" href="?page={{items.next_page_number}}{% if query %}&q={{ query }}{% endif %}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" style="background-color: #ffd536; color: #1e415e; border: #1e415e;"><span>&raquo;</span></a>
                </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    {% endif %}