blog-management-system-master/blog-management-system-master/blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    url(r'^result/$', search, name='search'),
    url(r'^blog-list/$', post_list, name='blog_list'),
    url(r'^blog-detail/(?P<slug>[-\w]+)/$', post_detail, name='blog_detail'),
    url(r'^category-detail/(?P<slug>[-\w]+)/$', category_detail, name='category_detail'),

    url(r'^new-post/$', new_post, name='new_post'),

    url(r'^post-list/$', post_list_admin, name='post_list_admin'),
    url(r'^edit-post/(?P<pk>\d+)/$', edit_post, name='edit_post'),
    url(r'^delete-post/(?P<pk>\d+)/$', delete_post, name='delete_post'),
]

blog-management-system-master/blog-management-system-master/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *
from blog.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home', home, name='home'),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog')),
    url(r'^login/', user_login, name="user_login"),
    url(r'^logout/', user_logout, name="user_logout"),
    url(r'^register/', user_register, name="user_register"),
    url(r'^final/', final, name="final"),
]

blog-management-system-master/blog-management-system-master/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Category(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    seo_title = models.CharField(max_length=60, null=True, blank=True)
    seo_description = models.CharField(max_length=165, null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class Post(models.Model):
    STATUS_CHOICES = (
        ('Published', 'Published'),
        ('Draft', 'Draft'),
    )
    title = models.CharField(max_length=250)
    body = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    seo_title = models.CharField(max_length=60, null=True, blank=True)
    seo_description = models.CharField(max_length=165, null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.CharField(max_length=10, default='Draft', choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog-management-system-master/blog-management-system-master/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body', 'category', 'seo_title', 'seo_description', 'status']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'seo_title': forms.TextInput(attrs={'class': 'form-control'}),
            'seo_description': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user

blog-management-system-master/blog-management-system-master/blog/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from example.config import pagination
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import *
from .forms import *


def user_login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if request.GET.get('next', None):
                return HttpResponseRedirect(request.GET['next'])
            return HttpResponseRedirect(reverse('blog:post_list_admin'))
        else:
            context['error'] = 'Username or password is invalid !!!'
            return render(request, 'auth/login.html', context)
    else:
        return render(request, 'auth/login.html', context)


def user_logout(request):
    if request.method == "POST":
        logout(request)
        return HttpResponseRedirect(reverse('user_login'))


@login_required(login_url='/login/')
def post_list(request):
    template = 'blog/post_list.html'
    object_list = Post.objects.filter(status='Published')

    pages = pagination(request, object_list, 1)

    context = {
        'items': pages[0],
        'page_range': pages[1],
    }
    return render(request, template, context)


@login_required(login_url='/login/')
def post_detail(request, slug):
    template = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, template, context)


@login_required(login_url='/login/')
def category_detail(request, slug):
    template = 'blog/category_detail.html'
    category = get_object_or_404(Category, slug=slug)
    post = Post.objects.filter(category=category, status='Published')
    context = {
        'category': category,
        'post': post,
    }
    return render(request, template, context)

@login_required(login_url='/login/')
def search(request):
    template = 'blog/post_list.html'
    query = request.GET.get('q')

    if query:
        result = Post.objects.filter(Q(title__icontains=query))
    else:
        result = Post.objects.filter(status='Published')
    pages = pagination(request, result, num=1)
    context = {
        'items': pages[0],
        'page_range': pages[1],
        'query': query,
    }
    return render(request, template, context)


@login_required(login_url='/login/')
def new_post(request):
    template = 'blog/new_post.html'
    form = PostForm(request.POST or None)
    try:
        if form.is_valid():
            form.save()
            messages.success(request, 'Blog post was saved to the database')

    except Exception as e:
        messages.warning(request, 'Blog post was not saved. Error: {}'.format(e))
    context = {
        'form': form,
    }
    return render(request, template, context)

@login_required(login_url='/login/')
def edit_post(request, pk):
    template = 'blog/new_post.html'
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        try:
            if form.is_valid():
                form.save()
                messages.success(request, 'Your Blog post has been updated')
        except Exception as e:
            messages.warning(request, 'Your post was not saved do to an error:{}'.format(e))

    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, template, context)


@login_required(login_url='/login/')
def delete_post(request, pk):
    template = 'blog/new_post.html'
    post = get_object_or_404(Post, pk=pk)
    try:
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            post.delete()
            messages.success(request, 'You have successfully deleted post')
        else:
            form = PostForm(instance=post)
    except Exception as e:
        messages.warning(request, 'The post could not be deleted. error:{}'.format(e))

    context = {
        'form': form,
        'post': post,
    }
    return render(request, template, context)


@login_required(login_url='/login/')
def post_list_admin(request):
    template = 'blog/post_list_admin.html'
    post = Post.objects.all()
    pages = pagination(request, post, 3)
    context = {
        'items': pages[0],
        'page_range': pages[1],
    }
    return render(request, template, context)

blog-management-system-master/blog-management-system-master/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block seo_title %}{{ category.seo_title }}{% endblock %}
{% block seo_description %}{{ category.seo_description }}{% endblock %}
{% block content %}
    <hr>
<h1><a href=""><u>{{ category.title }}</u></a></h1>
<p>{{ category.description }}</p>
    <hr>

    {% for item in post %}
        <h2><a href=""><u>{{ item.title }}</u></a> </h2>
        <p>{{ item.body }}</p>
    {% endfor %}
{% endblock %}

blog-management-system-master/blog-management-system-master/templates/blog/new_post.html
{% extends 'base.html' %}

{% block content %}
<hr>
    <div class="offset-3 col-md-6">

    {% with url_name=request.resolver_match.url_name %}
        {% if url_name == 'new_post' %}
            <h2><u>Add a New Post</u></h2>
        {% elif url_name == 'edit_post' %}
            <h2><u>Edit Post: {{ post }}</u></h2>
        {% else %}
            <h2><u>Delete Post: {{ post }}</u></h2>
        {% endif %}
    {% endwith %}
    {% if messages %}
        {% for msg in messages %}
            <div {% if msg.tags %} class="alert alert-{{ msg.tags }} alert-dismissible" {% endif %} role="alert">
            <a href="" class="close" data-dismiss="alert">&times;</a>
            <strong>{{ msg }}</strong>
            </div>
        {% endfor %}
    {% else %}
        <div class="jumbotron">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {% for field in form %}
                    <label><b>{{ field.label_tag }}</b></label>
                    {{ field }}<br>
                {% endfor %}
            </div>

            {% with url_name=request.resolver_match.url_name %}
                {% if url_name == 'new_post' %}
                    <button  class="btn btn-primary float-right" type="submit">Save</button>
                {% elif url_name == 'edit_post' %}
                    <button class="btn btn-warning float-right" type="submit">Update</button>
                {% else %}
                    <button class="btn btn-danger float-right" type="submit">Delete</button>
                {% endif %}
            {% endwith %}
        </form>
        </div>
    {% endif %}
    </div>

{% endblock %}

blog-management-system-master/blog-management-system-master/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block seo_title %}{% endblock %}
{% block seo_description %}{% endblock %}

{% block content %}

<h1>Title:   <a href="" style="color: deepskyblue">{{ post.title }}</a></h1>
    <h2>Category:   <a  style="color: deepskyblue" href="{% url 'blog:category_detail' slug=post.category.slug %}">{{ post.category }}</a></h2>
    <h3>Status:   <a href="" style="color: deepskyblue">{{ post.status }}</a></h3>
{% endblock %}

blog-management-system-master/blog-management-system-master/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
{% include 'pagination.html' %}
{% for obj in items %}
<hr>
    <div class="container">
    <div class="jumbotron">
    <h1><u><a href="{% url 'blog:blog_detail' slug=obj.slug %}">{{ obj.title }}</a></u></h1>
    <p><strong>{{ obj.body }}</strong></p><hr>
    <p><b><u><a href="{% url 'blog:category_detail' slug=obj.category.slug %}">{{ obj.category }}</a></u></b><p>
    </div>
    </div>
{% endfor %}

{% include 'pagination.html' %}
{% endblock %}

blog-management-system-master/blog-management-system-master/templates/blog/post_list_admin.html
{% extends 'base.html' %}
{% block content %}

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">PK</th>
            <th scope="col">TITLE</th>
            <th scope="col">SLUG</th>
            <th scope="col">STATUS</th>
            <th scope="col">SEO_TITLE</th>
            <th scope="col">SEO_DESCRIPTION</th>
            <th scope="col">Detail</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
            <tr>
                <th>{{ item.pk }}</th>
                <th>{{ item.title }}</th>
                <th>{{ item.slug }}</th>
                <th>{{ item.status }}</th>
                <th>{% if item.seo_title %}Yes{% else %}No{% endif %}</th>
                <th>{% if item.seo_description %}Yes{% else %}No{% endif %}</th>
                <th><a href="/blog/blog-list/?page={{ item.id }}"><button class="btn btn-outline-primary">Detail</button></a></th>
                <th><a href="{% url 'blog:edit_post' pk=item.pk %}"><button class="btn btn-outline-warning">Edit</button></a></th>
                <th><a href="{% url 'blog:delete_post' pk=item.pk %}"><button class="btn btn-outline-danger">Delete</button></a></th>
            </tr>
        {% endfor %}
    </tbody>
</table>

    {% include 'pagination.html' %}
{% endblock %}